### ISSUE TITLE
sflj jdk backend does not recognize class name

### ISSUE THREAD

**Issue by Frontrider** [oshai/kotlin-logging#351] opened 2023-08-17 20:14 UTC
These are the log messages that I'm seeing. This is not the class that I was expecting, and there does not seem to be a way to change it.

`Aug 17, 2023 9:51:14 PM io.github.oshai.kotlinlogging.KLogger$DefaultImpls atInfo$default`

This is my dependency setup:

```
[versions]
sflj = "2.0.7"
kotlin-logging = "5.0.1"

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "sflj" }
slf4j-jdk = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "sflj" }


[bundles]
logging = ["kotlin-logging","slf4j-jdk","slf4j"]
```

Most likely an issue with the JDK backend (so may be treated as invalid), but doing this can't provide a fix for it  for some reason:
`protected val logger = KotlinLogging.logger("name of logger")`

Replaced the backend as a fix, but leaving it here as a reference.

**Comment by oshai** [comment] 2023-08-17 20:26
If you're using log4j it might be related to https://github.com/oshai/kotlin-logging/pull/332.
Anyway, if you can add a way to reproduce it I will be able to further investigate it.

**Comment by oshai** [comment] 2023-08-17 20:37
Btw - have you tried the latest version of jotlin-logging?

**Comment by Frontrider** [comment] 2023-08-23 17:33
Exactly the same.
`[Wed Aug 23 19:31:42 CEST 2023] FINE: io.github.oshai.kotlinlogging.KLogger$DefaultImpls atDebug$default - `

**Comment by oshai** [comment] 2023-08-23 18:02
I suspect what printed is location info and not logger name.
If you can provide a way to reproduce it (github repo) I will be able to further debug it.

**Comment by oshai** [comment] 2023-11-27 09:49
Most likely this is fixed in 5.1.1 as part of #332 .

**Comment by ennioVisco** [comment] 2024-02-14 11:48
I still have this issue, any other?

**Comment by oshai** [comment] 2024-02-14 12:18
Can you please create a way to reproduce it?

**Comment by ennioVisco** [comment] 2024-02-14 12:32
> Can you please create a way to reproduce it?

I'm investigating because I just migrated from V3.

It could be I have to change something in slf4j.

**Comment by ennioVisco** [comment] 2024-02-14 14:28
> > Can you please create a way to reproduce it?
> 
> I'm investigating because I just migrated from V3.
> 
> It could be I have to change something in slf4j.

Ok, that was the issue. It seems to work and the issue can be closed IMHO.

**Comment by oshai** [comment] 2024-02-14 15:18
Any more details on how it was fixed?

**Comment by ennioVisco** [comment] 2024-02-14 15:19
> Any more details on how it was fixed?

Tbh I just updated the other deps and cleaned the gradle caches. I wish I could tell you more, but it was just this for me :)

**Closed** 2024-02-14 15:21 UTC
